on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: yolo
        #env:
          #VITE_BASE_PATH: ${{ vars.ENV_VAR_ONE }}
        run: echo "vars.ENV_VAR_ONE = [${{ vars.ENV_VAR_ONE }}]"
