on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    environment:
      name: test_env

    steps:
      - name: print var
        #env:
          #VITE_BASE_PATH: ${{ vars.ENV_VAR_ONE }}
        run: echo "vars.ENV_VAR_ONE = [${{ vars.ENV_VAR_ONE }}]"
        
      - name: print secret
        run: echo "secrets.SEC_ONE = [${{ secrets.SEC_ONE }}]"
