on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: my-pages
          path: .

      - name: Deploy pages
        uses: actions/deploy-pages@v4

      - name: List dir
        run: ls -lha .
