on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: pwd
      - name: step2
        run: ls -lha ..
      - name: step3
        run: ls -lha ../..
      - name: step4
        run: ls -lha ../../..
